name: Typescript

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: enable pnpm
        run: corepack enable
      - name: install dependencies
        run: pnpm i
      - name: run tests
        run: pnpm run test

  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: enable pnpm
        run: corepack enable
      - name: install dependencies
        run: pnpm i
      - name: run build
        run: pnpm run build